[package]
name = "data_restore"
version = "0.1.0"
edition = "2018"

[dependencies]
num = { version = "0.2", features = ["serde"] }
tiny-keccak = "1.4.2"
ethabi = "9.0.0"
web3 = "0.10.0"
hex = "0.4"
log = "0.4"
serde_json = "1.0.0"
env_logger = "0.6"
failure = "0.1"
clap = "2.33.0"
futures = { version = "0.3", features = ["compat"] }
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
tokio = { version = "0.2", features = ["full"] }

plasma = { path = "../../lib/plasma", version = "0.1.1" }
models = { path = "../../lib/models", version = "0.0.1" }
storage = { path = "../../lib/storage", version = "0.0.1" }
zksync_crypto = { path = "../../lib/crypto", version = "0.1.0" }
zksync_utils = { path = "../../lib/utils", version = "0.1.0" }
zksync_config = { path = "../../lib/config", version = "0.1.0" }
zksync_contracts = { path = "../../lib/contracts", version = "0.1.0" }
