[package]
name = "data_restore"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
num = { version = "0.2", features = ["serde"] }
tiny-keccak = "1.4.2"
ethabi = "12.0.0"
web3 = "0.13.0"
hex = "0.4"
log = "0.4"
serde_json = "1.0.0"
env_logger = "0.6"
failure = "0.1"
clap = "2.33.0"
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }
tokio = { version = "0.2", features = ["full"] }

plasma = { path = "../../lib/plasma", version = "1.0" }
models = { path = "../../lib/models", version = "1.0" }
storage = { path = "../../lib/storage", version = "1.0" }
zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_contracts = { path = "../../lib/contracts", version = "1.0" }
