[package]
name = "sandbox"
version = "0.0.1"

[dependencies]
serde_json = {version = "1.0.39", features = ["arbitrary_precision"]}
#serde_json = "1.0.39"
bigdecimal = { version = "0.1.0", features = ["serde"]}
serde = "1.0.90"
serde_derive = "1.0.90"