[package]
name = "gen_token_add_contract"
version = "0.1.0"
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models = { path = "../../lib/models", version = "0.0.1" }
zksync_utils = { path = "../../lib/utils", version = "0.1.0" }

handlebars = "3.0.1"
