[package]
name = "plasma"
version = "0.1.1"
edition = "2018"

authors = [
    "Alex Gluchowski <alex@gluchowski.net>",
    "Alex Vlasov <alex.m.vlasov@gmail.com>"
]

[dependencies]
circuit = { path = "../circuit" }
models = { path = "../models" }
merkle_tree = { path = "../merkle_tree" }
ff = { package = "ff_ce", version = "0.6.0", features = ["derive"] }
pairing = { package = "pairing_ce", version = "0.17.0" }
bellman = { package = "bellman_ce", version = "0.3.0" }
bigdecimal = { version = "0.1.0", features = ["serde"]}
sapling_crypto = { package = "sapling-crypto_ce", version = "0.0.5" }
lazy_static = "1.2.0"
serde = "1.0.90"
serde_derive = "1.0.90"
hex = "0.3.2"
rust-crypto = "0.2"
rand = "0.4"
time = "0.1"

