kind: pipeline
type: docker
name: default

clone:
    depth: 10

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./contracts/node_modules
      - ./js/client/node_modules
      - ./js/explorer/node_modules
      - ./target/cargo
      - ./keys

- name: init
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - ci-prepare-env.sh
  - zksync env ci
  - zksync yarn
  depends_on:
  - restore-cache

- name: build-contracts
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - zksync build-contracts
  depends_on:
  - init

- name: rust-release-build
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - f cargo build --release
  depends_on:
  - build-contracts

- name: build-and-publish-server
  image: docker
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker build --build-arg BINARY=/drone/src/target/x86_64-unknown-linux-musl/release/server -t $REPO:${DRONE_COMMIT_SHA:0:8} -t $REPO:${DRONE_COMMIT_SHA:0:8} -f $DOCKERFILE .
  - docker push $REPO:${DRONE_COMMIT_SHA:0:8}
  - docker push $REPO:latest
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    DOCKERFILE: ./docker/server/Dockerfile
    REPO: matterlabs/server
  depends_on:
  - rust-release-build
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock

- name: build-and-publish-prover
  image: docker
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker build --build-arg BINARY=/drone/src/target/x86_64-unknown-linux-musl/release/prover -t $REPO:${DRONE_COMMIT_SHA:0:8} -t $REPO:latest -f $DOCKERFILE .
  - docker push $REPO:${DRONE_COMMIT_SHA:0:8}
  - docker push $REPO:latest
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    DOCKERFILE: ./docker/prover/Dockerfile
    REPO: matterlabs/prover
  depends_on:
  - rust-release-build
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
  - fk/test-branch
  event:
  - push
