kind: pipeline
type: docker
name: tests
clone:
    depth: 10
volumes:
  - name: cache
    host:
      path: /tmp/cache
services:
  - name: geth
    image: matterlabs/geth:latest
  - name: postgres
    image: postgres:10.4
trigger:
  event:
  - pull_request
steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./contracts/node_modules
      - ./js/client/node_modules
      - ./js/explorer/node_modules
      - ./target/cargo
      - ./keys
- name: init
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - ci-prepare-env.sh
  - zksync env ci
  - zksync yarn
  - zksync db-wait
  - zksync db-setup
  depends_on:
  - restore-cache
- name: build-contracts
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - zksync build-contracts
  depends_on:
  - init
- name: rust-checks
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - cargo fmt -- --check
  - f cargo clippy --tests --benches -- -D warnings
  depends_on:
  - build-contracts
- name: rust-tests
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - f cargo test
  - zksync circuit-tests
  - zksync prover-tests
  - zksync db-test
  depends_on:
  - rust-checks
- name: deploy-test
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - zksync genesis
  - zksync redeploy
  - zksync integration-testkit
  depends_on:
  - rust-tests
- name: contract-test
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - zksync test-contracts
  depends_on:
  - build-contracts
- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./contracts/node_modules
      - ./js/client/node_modules
      - ./js/explorer/node_modules
      - ./target/cargo
      - ./keys
  depends_on:
     - init
     - rust-checks
---
# This pipeline builds and publishes server and prover images.
# TODO: deploy staging.
kind: pipeline
type: docker
name: update-stage
clone:
    depth: 10
volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker-sock
    host:
      path: /var/run/docker.sock
trigger:
  branch:
  - dev
  event:
  - push
steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./contracts/node_modules
      - ./js/client/node_modules
      - ./js/explorer/node_modules
      - ./target/cargo
      - ./keys
- name: init
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - ci-prepare-env.sh
  - zksync env ci
  - zksync yarn
  depends_on:
  - restore-cache
- name: build-contracts
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - zksync build-contracts
  depends_on:
  - init
- name: nginx-build-and-publish
  image: docker
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker build -t $REPO:${DRONE_COMMIT_SHA:0:8} -t $REPO:latest -f $DOCKERFILE .
  - docker push $REPO:${DRONE_COMMIT_SHA:0:8}
  - docker push $REPO:latest
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    DOCKERFILE: ./docker/nginx/Dockerfile
    REPO: matterlabs/nginx
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  depends_on:
  - build-contracts
- name: rust-release-build
  image: matterlabs/ci
  commands:
  - export ZKSYNC_HOME=`pwd`
  - export PATH=$ZKSYNC_HOME/bin:$PATH
  - export CARGO_HOME=$ZKSYNC_HOME/target/cargo
  - f cargo build --release
  depends_on:
  - build-contracts
- name: server-build-and-publish
  image: docker
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker build --build-arg BINARY=/drone/src/target/x86_64-unknown-linux-musl/release/server -t $REPO:${DRONE_COMMIT_SHA:0:8} -t $REPO:${DRONE_COMMIT_SHA:0:8} -f $DOCKERFILE .
  - docker push $REPO:${DRONE_COMMIT_SHA:0:8}
  - docker push $REPO:latest
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    DOCKERFILE: ./docker/server/Dockerfile
    REPO: matterlabs/server
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  depends_on:
  - rust-release-build
- name: prover-build-and-publish
  image: docker
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker build --build-arg BINARY=/drone/src/target/x86_64-unknown-linux-musl/release/prover -t $REPO:${DRONE_COMMIT_SHA:0:8} -t $REPO:latest -f $DOCKERFILE .
  - docker push $REPO:${DRONE_COMMIT_SHA:0:8}
  - docker push $REPO:latest
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    DOCKERFILE: ./docker/prover/Dockerfile
    REPO: matterlabs/prover
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  depends_on:
  - rust-release-build
