[workspace]
members = [
    "src/data_restore",
    "src/key_generator",
    "src/merkle_tree",
    "src/eth_client",
    "src/models",
    "src/plasma",
    "src/prover",
    "src/sandbox",
    "src/server",
    "src/storage",
    "src/circuit",
    "src/franklincircuit",
    "src/franklinmodels",
]
