[workspace]
members = [
    "core/bin/data_restore",
    "core/bin/key_generator",
    "core/bin/server",
    "core/bin/prover",
    "core/bin/tok_cli",

    "core/lib/circuit",
    "core/lib/crypto_exports",
    "core/lib/eth_client",
    "core/lib/models",
    "core/lib/plasma",
    "core/lib/storage",
    "core/lib/vlog",

    "core/tests/testkit",
    "core/tests/loadtest",
]
