[workspace]
members = [
    "core/key_generator",
    "core/merkle_tree",
    "core/eth_client",
    "core/models",
    "core/plasma",
    "core/prover",
    "core/server",
    "core/storage",
    "core/franklincircuit",
    "core/franklinmodels",
]
