[workspace]
members = [
    "core/key_generator",
    "core/eth_client",
    "core/plasma",
    "core/prover",
    "core/server",
    "core/storage",
    "core/franklincircuit",
    "core/franklinmodels",
    "core/franklin_key_generator",
]
