version: '3.2'
services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    volumes:
    - type: bind
      source: ./volumes/postgres
      target: /var/lib/postgresql/data
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
  geth:
    image: "matterlabs/geth:latest"
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
    - type: bind
      source: ./volumes/geth
      target: /var/lib/geth/data
  dev-liquidity-token-watcher:
    image: "matterlabs/dev-liquidity-token-watcher:latest"
    ports:
      - "9975:9975"
    volumes:
      - ./etc/tokens/:/etc/tokens

  dev-ticker:
    image: "matterlabs/dev-ticker:latest"
    ports:
      - "9876:9876"
  tesseracts:
    image: "adria0/tesseracts"
    command: --cfg /tesseracts.toml -vvv
    ports:
      - "8000:8000"
    volumes:
    - ./etc/tesseracts/tesseracts.toml:/tesseracts.toml
    - type: bind
      source: ./volumes/tesseracts
      target: /var/lib/tesseracts/data

  zk:
    build:
      context: .
      dockerfile: docker/zk/Dockerfile
    volumes:
      - .:/usr/src/zksync

  runner:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/matter-labs/zksync-dev
      RUNNER_NAME: example-name
      RUNNER_TOKEN: AB5IZDXCJNZXBCONB6HESOK77LQYI
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_GROUP: my-group
      ORG_RUNNER: 'false'
      LABELS: linux,x64
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/runner:/tmp/runner
      - .:/usr/src/zksync
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
