version: '3.2'
services:
  server:
    image: "gluk64/franklin:server"
    env_file: etc/env/local.env
    environment:
      - DATABASE_URL=postgres://postgres@postgres/plasma
      - WEB3_URL=http://geth:8545
    ports:
      - "80:3000"
  prover:
    image: "gluk64/franklin:prover"
    env_file: etc/env/local.env
    environment:
      - PROVER_DATABASE_URL=postgres://postgres@postgres/plasma
    volumes:
      - type: bind
        source: ./keys
        target: /keys
  postgres:
    image: "postgres:10.4"
    ports:
      - "5432:5432"
    volumes:
    - type: bind
      source: ./volumes/postgres
      target: /var/lib/postgresql/data
  geth:
    image: "gluk64/franklin:geth"
    # image: "ethereum/client-go"
    # command: '--rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=456719 --rpc --rpcaddr="0.0.0.0"'
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
    - type: bind
      source: ./volumes/geth
      target: /var/lib/geth/data
