version: '3.2'
services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust

  geth:
    image: "matterlabs/geth:latest"
    ports:
      - "8545:8545"
      - "8546:8546"

  dev-ticker:
    image: "matterlabs/dev-ticker:latest"
    ports:
      - "9876:9876"
  dev-liquidity-token-watcher:
    image: "matterlabs/dev-liquidity-token-watcher:latest"
    ports:
      - "9975:9975"
    volumes:
      - ./etc/tokens/:/etc/tokens

  tesseracts:
    image: "adria0/tesseracts"
    command: --cfg /tesseracts.toml -vvv
    ports:
      - "8000:8000"
  zk:
    build:
      context: .
      dockerfile: docker/zk/Dockerfile
    depends_on:
      - postgres
      - geth
      - dev-ticker
      - dev-liquidity-token-watcher
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/zksync
      - /usr/src/cache:/usr/src/cache
      - /usr/src/keys:/usr/src/keys
    environment:
      - IN_DOCKER=true
      - CACHE_DIR=/usr/src/cache
      - CI=1
