[package]
name = "key_generator"
version = "0.1.1"
edition = "2018"

authors = [
    "Alex Gluchowski <alex@gluchowski.net>",
    "Alex Vlasov <alex.m.vlasov@gmail.com>"
]

[dependencies]
crypto_exports = { path = "../../lib/crypto_exports", version = "0.1.0" }
models = { path = "../../lib/models", version = "0.0.1" }
circuit= { path = "../../lib/circuit", version = "0.1.1" }
zksync_config = { path = "../../lib/config", version = "0.1.0" }
zksync_crypto = { path = "../../lib/crypto", version = "0.1.0" }
zksync_prover_utils = { path = "../../lib/prover_utils", version = "0.1.0" }
zksync_utils = { path = "../../lib/utils", version = "0.1.0" }

time = "0.1"
hex = "0.4"
rust-crypto = "0.2"
log = "0.4"
env_logger = "0.6"
clap = "2.33.0"
handlebars = "3.0.1"
serde_json = "1.0.0"
