[package]
name = "priority_op_tx_hashes_migration"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
anyhow = "1.0"
tokio = { version = "0.2", features = ["full"] }
sqlx = { version = "0.4.2", default-features = false, features = [
    "runtime-tokio-native-tls",
    "macros",
    "postgres",
    "bigdecimal",
    "chrono",
    "json",
    "offline",
] }
parity-crypto = { version = "0.6.2", features = ["publickey"] }
