apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gluk64/franklin:server
          imagePullPolicy: Always
          ports: 
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: franklin-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prover
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prover
  template:
    metadata:
      labels:
        app: prover
    spec:
      containers:
        - name: prover
          image: gluk64/franklin:prover
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: franklin-secret
