# Part of CI pipeline
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${KUBE_CA_DATA}
    server: ${KUBE_SERVER}
  name: default
contexts:
- context:
    cluster: default
    user: ${KUBE_USER}
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: ${KUBE_USER}
  user:
    token: ${KUBE_TOKEN}
