apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ZKSYNC_ENV}-prover-${BLOCK_CHUNK_SIZES}
  namespace: ${ZKSYNC_ENV}
  labels:
    app: ${ZKSYNC_ENV}-prover-${BLOCK_CHUNK_SIZES}
spec:
  selector:
    matchLabels:
      app: ${ZKSYNC_ENV}-prover-${BLOCK_CHUNK_SIZES}
  template:
    metadata:
      labels:
        app: ${ZKSYNC_ENV}-prover-${BLOCK_CHUNK_SIZES}
    spec:
      volumes:
      - name: keys-dir
        hostPath:
          path: /home/docker
      containers:
      - name: ${ZKSYNC_ENV}-prover-${BLOCK_SIZE_CHUNKS}
        image: matterlabs/prover:${IMAGE_TAG}
        imagePullPolicy: Always
        resources: ${PROVER_CONTAINER_RESOURCES}
        volumeMounts:
        - name: keys-dir
          mountPath: /keys
          readOnly: false
        env:
        - name: SUPPORTED_BLOCK_CHUNKS_SIZES
          value: "${SUPPORTED_BLOCK_CHUNKS_SIZES}"
        - name: SUPPORTED_BLOCK_CHUNKS_SIZES_SETUP_POWERS
          value: "${SUPPORTED_BLOCK_CHUNKS_SIZES_SETUP_POWERS}"
        - name: BLOCK_CHUNK_SIZES
          value: "${BLOCK_CHUNK_SIZES}"
        - name: KEY_DIR
          value: "${KEY_DIR}"
        - name: ACCOUNT_TREE_DEPTH
          value: "${ACCOUNT_TREE_DEPTH}"
        - name: BALANCE_TREE_DEPTH
          value: "${BALANCE_TREE_DEPTH}"
        - name: PROVER_SERVER_URL
          value: "${PROVER_SERVER_URL}"
        - name: REQ_SERVER_TIMEOUT
          value: "${REQ_SERVER_TIMEOUT}"
        - name: RUST_BACKTRACE
          value: "${RUST_BACKTRACE}"
        - name: RUST_LOG
          value: "${RUST_LOG}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      terminationGracePeriodSeconds: 20
