apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ZKSYNC_ENV}-prover-${BLOCK_SIZE_CHUNKS}
  namespace: ${ZKSYNC_ENV}
  labels:
    app: ${ZKSYNC_ENV}-prover-${BLOCK_SIZE_CHUNKS}
spec:
  selector:
    matchLabels:
      app: ${ZKSYNC_ENV}-prover-${BLOCK_SIZE_CHUNKS}
  template:
    metadata:
      labels:
        app: ${ZKSYNC_ENV}-prover-${BLOCK_SIZE_CHUNKS}
    spec:
      volumes:
      - name: keys-dir
        hostPath:
          path: /home/docker
      containers:
      - name: ${ZKSYNC_ENV}-prover-${BLOCK_SIZE_CHUNKS}
        image: matterlabs/prover:${IMAGE_TAG}
        imagePullPolicy: Always
        volumeMounts:
        - name: keys-dir
          mountPath: /keys
          readOnly: false
        env:
        - name: RUST_BACKTRACE
          value: "${RUST_BACKTRACE}"
        - name: CONTRACT_ADDR
          value: "${CONTRACT_ADDR}"
        - name: KEY_DIR
          value: "${KEY_DIR}"
        - name: TX_BATCH_SIZE
          value: "${TX_BATCH_SIZE}"
        - name: MAX_OUTSTANDING_TXS
          value: "${MAX_OUTSTANDING_TXS}"
        - name: DB_POOL_SIZE
          value: "${DB_POOL_SIZE}"
        - name: ACCOUNT_TREE_DEPTH
          value: "${ACCOUNT_TREE_DEPTH}"
        - name: BLOCK_SIZE_CHUNKS
          value: "${BLOCK_SIZE_CHUNKS}"
        - name: KEYS_SPACE_URL
          value: "${KEYS_SPACE_URL}"
        - name: PROVER_SERVER_URL
          value: "${PROVER_SERVER_URL}"
        - name: REQ_SERVER_TIMEOUT
          value: "${REQ_SERVER_TIMEOUT}"
        - name: BLOCK_CHUNK_SIZES
          value: "${BLOCK_CHUNK_SIZES}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      terminationGracePeriodSeconds: 20
