apiVersion: apps/v1
kind: Deployment
metadata:
  name: prover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prover
  template:
    metadata:
      labels:
        app: prover
    spec:
      containers:
        - name: prover
          image: gluk64/franklin:prover
          imagePullPolicy: Always
          resources:
            requests:
              memory: "30Gi"
          envFrom:
          - secretRef:
              name: franklin-secret
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      terminationGracePeriodSeconds: 5
      nodeSelector:
        doks.digitalocean.com/node-pool: prover
