apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: ${ZKSYNC_ENV}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ${ZKSYNC_ENV}-server
          servicePort: 3000
      - path: /jsrpc
        backend:
          serviceName: ${ZKSYNC_ENV}-server
          servicePort: 3030
      - path: /jsrpc-ws
        backend:
          serviceName: ${ZKSYNC_ENV}-server
          servicePort: 3031
    host: ${SERVER_API_HOST}
---
apiVersion: v1
kind: Service
metadata:
  name: ${ZKSYNC_ENV}-nginx
  namespace: ${ZKSYNC_ENV}
  labels:
    app: ${ZKSYNC_ENV}-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ${ZKSYNC_ENV}-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: ${ZKSYNC_ENV}-server
  namespace: ${ZKSYNC_ENV}
  labels:
    app: ${ZKSYNC_ENV}-server
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: ${ZKSYNC_ENV}-server-rest
  - port: 3030
    targetPort: 3030
    protocol: TCP
    name: ${ZKSYNC_ENV}-server-jsrpc
  - port: 3031
    targetPort: 3031
    protocol: TCP
    name: ${ZKSYNC_ENV}-server-jsrpc-ws
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: ${ZKSYNC_ENV}-prover-server-port
  selector:
    app: ${ZKSYNC_ENV}-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ZKSYNC_ENV}-nginx
  namespace: ${ZKSYNC_ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${ZKSYNC_ENV}-nginx
  template:
    metadata:
      labels:
        app: ${ZKSYNC_ENV}-nginx
    spec:
      containers:
        - name: ${ZKSYNC_ENV}-nginx
          image: matterlabs/nginx:${ZKSYNC_ENV}-${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ZKSYNC_ENV}-server
  namespace: ${ZKSYNC_ENV}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ${ZKSYNC_ENV}-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${ZKSYNC_ENV}-server
    spec:
      containers:
        - name: server
          image: matterlabs/server:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 3030
            - containerPort: 3031
            - containerPort: 8088
          envFrom:
            - secretRef:
                name: ${ZKSYNC_ENV}-secret
          env:
          - name: ZKSYNC_ENV
            value: "${ZKSYNC_ENV}"
