apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
  - host: testnet.matter-labs.io
    http:
      paths:
      - path: /
        backend:
          serviceName: ${ZKSYNC_ENV}-server
          servicePort: 3000
      - path: /jsrpc
        backend:
          serviceName: ${ZKSYNC_ENV}-server
          servicePort: 3030
      - path: /jsrpc-ws
        backend:
          serviceName: ${ZKSYNC_ENV}-server
          servicePort: 3031
---
apiVersion: v1
kind: Service
metadata:
  name: ${ZKSYNC_ENV}-nginx
  labels:
    app: ${ZKSYNC_ENV}-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ${ZKSYNC_ENV}-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ZKSYNC_ENV}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${ZKSYNC_ENV}-nginx
  template:
    metadata:
      labels:
        app: ${ZKSYNC_ENV}-nginx
    spec:
      containers:
        - name: ${ZKSYNC_ENV}-nginx
          image: matterlabs/nginx:${ZKSYNC_ENV}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      nodeSelector:
        doks.digitalocean.com/node-pool: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ZKSYNC_ENV}-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ${ZKSYNC_ENV}-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${ZKSYNC_ENV}-server
    spec:
      containers:
        - name: server
          image: matterlabs/server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 3030
            - containerPort: 3031
          envFrom:
            - secretRef:
                name: ${ZKSYNC_ENV}-secret
          env:
          - name: ZKSYNC_ENV
            value: "${ZKSYNC_ENV}"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      nodeSelector:
        doks.digitalocean.com/node-pool: server
