# Configuration for the core API servers.

# Common configuration options for the API
[api.common]
# Size of LRU caches for requests
caches_size=10000

# Configuration for the admin API server
[api.admin_api]
url="http://127.0.0.1:8080"
port=8080
# secret_auth is set in `private.toml`

# Configuration for the REST API server
[api.rest]
port=3001

# Configuration for the JSON RPC server
[api.json_rpc]
# Port for the HTTP RPC API.
http_port=3030
# Port for the WebSocket RPC API.
ws_port=3031

# Configuration for the core private server.
[api.private]
port=8090
url="http://127.0.0.1:8090"

# Configuration for the prover server.
[api.prover]
port=8088
url="http://127.0.0.1:8088"

# Configuration for the prometheus exporter server.
[api.prometheus]
port=3312
