[fee_ticker]
# Indicator of the API to be used for getting token prices.
# Only supported options currently are "CoinGecko" and "CoinMarketCap".
token_price_source="CoinGecko"
# Set to be a development mock server.
coinmarketcap_base_url="http://127.0.0.1:9876"
# Set to be a development mock server.
# Use https://api.coingecko.com/ for production.
coingecko_base_url="http://127.0.0.1:9876"
# Coefficient for the fee price for fast withdrawal requests.
fast_processing_coeff=10.0
# List of tokens not suitable for paying fees.
disabled_tokens=[
    "38A2fDc11f526Ddd5a607C1F251C065f40fBF2f7" # PHNX
]
# List of tokens for which subsidions are disabled.
not_subsidized_tokens=[
    "2b591e99afe9f32eaa6214f7b7629768c40eeb39", # HEX
    "34083bbd70d394110487feaa087da875a54624ec"  # Some sample token
]
