# Options for L1-based ForcedExit utility
[forced_exit_requests]
# Whether the feature is enabled. Used to be able to quickly stop serving FE requests
# in times of attacks or upgrages  
enabled=true

# The price that will be demanded from a user is equal to 
# price_for_withdrawal * price_scaling
price_scaling_factor=1.6

max_tokens_per_request=10

# Recommended interval to send the transaction in milliseconds
recomended_tx_interval=300

# How many times the maximum acceptable interval will be longer 
# than the recommended interval
tx_interval_scaling_factor=1.5
