# Options for L1-based ForcedExit utility
[forced_exit_requests]
# Whether the feature is enabled. Used to be able to quickly stop serving FE requests
# in times of attacks or upgrages  
enabled=true

max_tokens_per_request=10

# Recommended interval to send the transaction in milliseconds
recomended_tx_interval=300

# How many times the maximum acceptable interval will be longer 
# than the recommended interval
tx_interval_scaling_factor=1.5

# Number of digits in id
digits_in_id=13

# Price per exit in wei (currently it's 0.03 ETH)
price_per_token=30000000000000000

# Wait confirmations
wait_confirmations=1

# The account of the ForcedExit sender
sender_account_address="0xe1faB3eFD74A77C23B426c302D96372140FF7d0C"
