# Whether to ask user about dangerous actions or not
zksync_action="dont_ask"

# Miscellaneous options for different infrastructure elements
[misc]
# Download setup files from SETUP_NETWORK_DIR if PROVER_DOWNLOAD_SETUP=1 or use local files if PROVER_DOWNLOAD_SETUP=0
prover_download_setup=false
# Network location of setup files
prover_setup_network_dir="-"

# Used to configure env for docker
docker_dummy_prover=false


# API key for the analytics script
etherscan_api_key="unset"

# Configuration for the fee seller script
max_liquidation_fee_percent=5
# fee_account_private_key is set in `private.toml`

reserve_fee_accumulator_address="unset"

established_assets_for_withdrawing_through_zksync="ETH,DAI,USDC"

# Format of logs in stdout could be "plain" for development purposes and "json" for production
log_format="plain"

sentry_url="unset"

# The address of the regenesis multisig smart contract
regenesis_multisig_address="0xAA7113B9de498556dC76eDFEFc57681083c861C1"

# The number of signatures needed for the regenesis to complete
regenesis_needed_signatures=3

# The list of partners signatures of which will be collected for the regenesis
regenesis_partners="0xB991c776AedacfA5a7e8CF3e7aD6CB6C1AcB9227,0x093Cf8450c5eE506aB865F68F5f8EB8C4C2073C2,0x0d2200E8Ff14516397E86Ad63670516D371Dc862,0x374Ac2A10cBCaE93d2aBBe468f0EDEF6768e65eEz"
