# Whether to ask user about dangerous actions or not
zksync_action="dont_ask"

# Miscellaneous options for different infrastructure elements
[misc]
# Download setup files from SETUP_NETWORK_DIR if PROVER_DOWNLOAD_SETUP=1 or use local files if PROVER_DOWNLOAD_SETUP=0
prover_download_setup=false
# Network location of setup files
prover_setup_network_dir="-"

# Used to configure env for docker
docker_dummy_prover=false


# API key for the analytics script
etherscan_api_key="unset"

# Configuration for the fee seller script
max_liquidation_fee_percent=5
# fee_account_private_key is set in `private.toml`

reserve_fee_accumulator_address="unset"

established_assets_for_withdrawing_through_zksync="ETH,DAI,USDC"

# Format of logs in stdout could be "plain" for development purposes and "json" for production
log_format="plain"

sentry_url="unset"

# The address of the regenesis multisig smart contract
regenesis_multisig_address="0xAA7113B9de498556dC76eDFEFc57681083c861C1"

# The address of the regenesis gnosis smart contract
regenesis_gnosis_address="0xbD5Ca6f189111A1befd4ffAa6F17f62D4535F254"

# The address of the new additional zkSync
new_additional_zksync_address="0x7fbaD9d9C9a1204F45FA38CcbF732B0930F8B582"

# Token in which we want accept fees for permissionless token listing
listing_fee_token="0x0000000000000000000000000000000000000000"

# The number of token (in wei) we want to be payed for listing a token
listing_fee=10000000000000000

# Listing cap, the maximum number of tokens which can be listed (2^16 - 100 by default)
listing_cap=65436

# The address which will receive funds from permissionless token listings
listing_treasury="0xaFe6A91979021206ad79F58562Eef4204720E2A3"

# The address of the token governance
listing_governance="0xaFe6A91979021206ad79F58562Eef4204720E2A3"

# The addresses of the security council gnosis smart contracts
security_council_2_weeks_address="0x7fbaD9d9C9a1204F45FA38CcbF732B0930F8B582"
security_council_1_week_address="0x7fbaD9d9C9a1204F45FA38CcbF732B0930F8B582"
security_council_3_days_address="0x7fbaD9d9C9a1204F45FA38CcbF732B0930F8B582"
