[package]
name = "server"
version = "0.0.1"

[[bin]]
name = "server"
path = "bin/server.rs"

[dependencies]
plasma = { path = ".." }

ff = { path = "../../ff", features = ["derive"] }
pairing = { path = "../../pairing" }
bellman = { path = "../../bellman" }
sapling-crypto = { path = "../../sapling-crypto" }

rand = "0.4"
hex = "0.3.2"
time = "0.1"
num-bigint = "0.2"
rust-crypto = "0.2"
fnv = "1.0.3"
ethabi = "6.1.0"
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
rustc-hex = "2.0.1"
futures = "0.1.25"
hyper = "0.12.16"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
serde_bytes = "0.10.4"

#r2d2 = "0.8.3"
#r2d2_postgres = "0.14.0"

im = "12.2.0"
priority-queue = "0.5.2"
num-traits = "0.2"

actix = "0.7.7"
actix-web = "0.7.14"

diesel = { version = "1.3.3", features = ["postgres", "serde_json", "r2d2"] }
bigdecimal = { version = "0.0.11", features = ["serde"]}
dotenv = "0.9.0"

ctrlc = { version = "3.1.1", features = ["termination"] }
signal-hook = "0.1.8"
