[package]
name = "server"
version = "0.0.1"

[dependencies]
plasma = { path = ".." }

ff = { path = "../../ff", features = ["derive"] }
pairing = { path = "../../pairing" }
bellman = { path = "../../bellman" }
sapling-crypto = { path = "../../sapling-crypto" }

rand = "0.4"
hex = "0.3.2"
time = "0.1"
num-bigint = "0.2"
rust-crypto = "0.2"
fnv = "1.0.3"
ethereum-types = "0.4.0"
ethabi = "6.1.0"
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
ethereum-tx-sign = "0.0.2"
rustc-hex = "2.0.1"

futures = "0.1.25"
futures-cpupool = "0.1.8"
crossbeam = "0.5.0"
crossbeam-utils = "0.6.1"
rayon = "1.0.3"
hyper = "0.12.16"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
serde_bytes = "0.10.4"
tokio = "0.1.13"
reqwest = "0.9.5"
smart-default = "0.3.0"

actix = "0.7.7"
actix-web = "0.7.14"

rlp = "0.3.0"
tiny-keccak = "1.4.2"
secp256k1 = "0.11.1"

diesel = { version = "1.3.3", features = ["postgres", "serde_json"] }
bigdecimal = { version = "0.0.11", features = ["serde"]}
dotenv = "0.9.0"

lazy_static = "1.2.0"
