# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"

# Import Plasma-specific SQL types
import_types = ["diesel::sql_types::*", "crate::models::plasma_sql::sql_types::*"]
