[package]
name = "get_block_data"
version = "0.1.0"
authors = ["perekopskiy <perekopskiy@dlit.dp.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }
zksync_eth_client = { path = "../../lib/eth_client", version = "1.0" }
zksync_config = { path = "../../lib/config", version = "1.0" }
tokio = { version = "0.2", features = ["full"] }
ethabi = "12.0.0"
anyhow = "1.0"
web3 = "0.13.0"
sqlx = { version = "0.4.2", default-features = false, features = [
    "runtime-tokio-native-tls",
    "macros",
    "postgres",
    "bigdecimal",
    "chrono",
    "json",
    "offline",
] }