[package]
name = "storage"
version = "0.0.1"

[dependencies]
plasma = { path = "../plasma" }
models = { path = "../models" }

fnv = "1.0.3"
serde_json = "1.0.33"
serde_derive = "1.0.80"
diesel = { version = "1.3.3", features = ["postgres", "serde_json", "r2d2"] }
bigdecimal = { version = "0.0.11", features = ["serde"]}
