name: CI lints

on:
  pull_request:
  push:
    branches:
    - staging
    - trying

jobs:
  ci-lint:
    runs-on: [self-hosted, CI-worker]

    steps:

      - uses: actions/checkout@v2

      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH

      - name: lints
        run: |
          ci_run zk
          ci_run zk fmt --check
          ci_run zk lint --check
