name: CI

on:
  push:
    branches: [ test-github-ci ]
  pull_request:
    branches: [ test-github-ci ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: cargo check
