name: Rust

on:
  push:
    branches: [ dev, test-github-ci ]
  pull_request:
    branches: [ dev, test-github-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo cargo check
