name: CI

on:
  pull_request:
  push:
    branches:
    - staging
    - trying

jobs:
  ci-all:
    # We currently have two self-hosted runners, one of which is marked "DEV-CI" and other one is marder "MAIN".
    # "MAIN" is the current CI runner, "DEV-CI" is currently used to experiment with CI optimizing.
    runs-on: [self-hosted, TEST]

    steps:

      - uses: actions/checkout@v2
      - name: start-services
        run: |
          docker-compose -f docker-compose-runner.yml down
          docker-compose -f docker-compose-runner.yml up --build -d geth postgres zk

      - name: start_sccache
        run: ci_run sccache --start-server

      - name: init
        run: |
          ci_run ln -s /usr/src/keys/setup keys/setup
          ci_run zk
          ci_run zk dummy-prover enable --no-redeploy
          ci_run zk init

      - name: liquidity-token
        run: docker-compose -f docker-compose-runner.yml restart dev-liquidity-token-watcher

      - name: lints
        run: ci_run sh infrastructure/ci-scripts/lints.sh

      - name: run-services
        run: ci_run sh infrastructure/ci-scripts/run_services.sh

      - name: integration-tests
        run: ci_run zk test integration all

      - name: integration-testkit
        run: ci_run zk test integration testkit

      - name: contracts-unit-tests
        run: ci_run zk test contracts

      - name: js-unit-tests
        run: ci_run zk test js

      - name: rust-unit-tests
        run: ci_run zk test rust

      - name: zksync-crypto-tests
        run: ci_run zk f cd /usr/src/zksync/sdk/zksync-crypto && zk f cargo test --release

      - name: cache
        run: ci_run sh infrastructure/ci-scripts/cache.sh
