name: Build and Deploy Stage
on:
  push:
    branches:
      - dev
      - breaking
      - hotfix/*
    tags:
      - hotfix-*

# Disable simultaneous deployments into stage
concurrency: deploy-stage

jobs:
  setup:
    name: Setup
    runs-on: [k8s, stage]
    outputs:
      image_tag: ${{ steps.set.outputs.shortRev }}
    steps:
      - uses: actions/checkout@v2
      - id: set
        run: echo "::set-output name=shortRev::$(git rev-parse --short HEAD)"

  build-images:
    name: Build and Push Docker Images
    needs: [setup]
    uses: ./.github/workflows/template-docker-build.yml
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_tag: ${{ needs.setup.outputs.image_tag }}

  # Reminder: when disabling the deploy stage - comment the whole job out!
  deploy:
    name: Deploy Stage environment
    runs-on: [k8s, deployer, stage]
    needs: [setup, build-images]
    steps:
      - name: Deploy
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Deploy
          token: ${{ secrets.GH_TOKEN }}
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 1m
          inputs: |
            {
              "environment": "stage",
              "image_tag": "${{ needs.setup.outputs.image_tag }}",
              "config_ref": "master"
            }
