name: CI

on:
  push:
    branches: [ test-github-ci, dev ]
  pull_request:
    branches: [ test-github-ci, dev ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: init
      - echo "::set-env name=ZKSYNC_HOME::$(pwd)"
      - echo "::set-env name=PATH::$($ZKSYNC_HOME/bin:$PATH)"
      - ci-prepare-env.sh
      - zksync env ci
      - zksync yarn

  services:
    geth:
      image: matterlabs/geth:latest
      ports:
        - 8545:8545
        - 8546:8546
      env:
        config: standard

    geth-fast:
      image: matterlabs/geth:latest
      ports:
        - 8545:8545
        - 8546:8546
      env:
        config: fast

    postgres:
      image: postgres:10.4
      ports:
        - 5432:5432
