name: Merge
on:
  repository_dispatch:
    type: [merge-upstream]

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.stage }}

      - name: Merge Upstream (@${{ github.event.client_payload.stage }})
        run: |
          git remote add upstream https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/matter-labs/zksync-dev.git
          git remote -v | sed -E 's/\/.*@/\/\/xxx@/'
          git fetch upstream ${{ github.event.client_payload.stage }}
