name: Promote to stage

on:
  push:
    branches: [ dev ]

jobs:
  build-images:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Get env from keybase
      uses: ./.github/actions/keybase-secrets
      with:
        repo: keybase://team/matter_labs/zk-secret
      env:
        KEYBASE_PAPERKEY: ${{ secrets.KEYBASE_PAPERKEY }}
        KEYBASE_USERNAME: ${{ secrets.KEYBASE_USERNAME }}

    - name: restore-selfhosted-runner-cache
      run: tar xf ~/runner-cache.tar

    - name: setup-env
      run: |
        echo "::set-env name=ZKSYNC_HOME::$(pwd)"
        echo "::set-env name=PATH::$(echo `pwd`/bin:$PATH)"
        echo "::set-env name=CI::1"

    - name: init
      run: |
        zksync yarn
        cp etc/tokens/{test,localhost}.json
        zksync verify-keys unpack

    - name: update-images
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        zksync update-images
        echo "::set-env name=IMAGE_TAG::$(f sh -c 'echo $IMAGE_TAG')"
