name: Build docker image
on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        description: 'DOCKERHUB_USER'
        required: true
      DOCKERHUB_TOKEN:
        description: 'DOCKERHUB_TOKEN'
        required: true
    inputs:
      image_tag:
        description: 'Tag of a built image to deploy'
        type: string
        required: true

jobs:
  build-images:
    name: Build and Push Docker Images
    env:
      image_tag: ${{ inputs.image_tag }}
    runs-on: [self-hosted, ci-runner]
    steps:
    - uses: actions/checkout@v2
    - name: setup-env
      run: |
        echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
        echo CI=1 >> $GITHUB_ENV
        echo $(pwd)/bin >> $GITHUB_PATH

    - name: start-services
      run: |
        docker-compose -f docker-compose-runner.yml up -d zk postgres

    - name: init
      run: |
        ci_run zk
        ci_run zk run yarn
        ci_run cp etc/tokens/{test,localhost}.json
        ci_run zk run verify-keys unpack
        ci_run zk db basic-setup

    - name: update-images
      run: |
        ci_run docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        ci_run zk docker push server

    - name: docker-down
      if: always()
      run: |
        docker-compose -f docker-compose-runner.yml down
